use_sim_time: true
max_particles: 2000
min_particles: 500
kld_err: 0.01
kld_z: 0.99
update_min_d: 0.2
update_min_a: 0.2
resample_interval: 2
transform_tolerance: 0.5
recovery_alpha_slow: 0.0001
recovery_alpha_fast: 0.1
laser_min_range: 0.05
laser_max_range: 12.0
