global_costmap:
  global_costmap:
    update_frequency: 1.0
    publish_frequency: 2.0
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.5
    plugins:
      - name: static_layer
        type: "nav2_costmap_2d::StaticLayer"
      - name: inflation_layer
        type: "nav2_costmap_2d::InflationLayer"

local_costmap:
  local_costmap:
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.5
    plugins:
      - name: obstacle_layer
        type: "nav2_costmap_2d::ObstacleLayer"
      - name: inflation_layer
        type: "nav2_costmap_2d::InflationLayer"
